copy %SYS_TRUSTED_CA% 			%JRE_SECURITY_FOLDER%
copy %SYS_TRUSTED_SITE_CA% 		%JRE_SECURITY_FOLDER%
copy %SYS_TRUSTED_CERT% 		%JRE_SECURITY_FOLDER%
copy %SYS_TRUSTED_SITE_CERT% 	%JRE_SECURITY_FOLDER%
copy %SYS_CLIENT_AUTH_CERT% 	%JRE_SECURITY_FOLDER%

copy %SYS_TRUSTED_CA% 			%JDK_SECURITY_FOLDER%
copy %SYS_TRUSTED_SITE_CA% 		%JDK_SECURITY_FOLDER%
copy %SYS_TRUSTED_CERT% 		%JDK_SECURITY_FOLDER%
copy %SYS_TRUSTED_SITE_CERT% 	%JDK_SECURITY_FOLDER%
copy %SYS_CLIENT_AUTH_CERT% 	%JDK_SECURITY_FOLDER%

copy %SYS_TRUSTED_SITE_CERT% 	%SYSTEM_SECURITY_FOLDER%
copy %SYS_TRUSTED_CERT% 		%SYSTEM_SECURITY_FOLDER%
copy %SYS_CLIENT_AUTH_CERT% 	%SYSTEM_SECURITY_FOLDER%

copy %SYS_TRUSTED_SITE_CERT% 	%USR_TRUSTED_SITE_CERTIFICATES%
copy %SYS_TRUSTED_CERT% 		%USR_TRUSTED_CERTIFICATES%