DEL /Q %JRE_SECURITY_FOLDER%\%TRUSTED_CA%
DEL /Q %JRE_SECURITY_FOLDER%\%TRUSTED_SITE_CA%

DEL /Q %JRE_SECURITY_FOLDER%\%TRUSTED_CERT%
DEL /Q %JRE_SECURITY_FOLDER%\%TRUSTED_SITE_CERT%
DEL /Q %JRE_SECURITY_FOLDER%\%CLIENT_AUTH_CERT%

DEL /Q %SYSTEM_SECURITY_FOLDER%\%TRUSTED_CERT%
DEL /Q %SYSTEM_SECURITY_FOLDER%\%TRUSTED_SITE_CERT%
DEL /Q %SYSTEM_SECURITY_FOLDER%\%CLIENT_AUTH_CERT%

DEL /Q %USR_SECURITY_FOLDER%\%TRUSTED_CERT%
DEL /Q %USR_SECURITY_FOLDER%\%TRUSTED_SITE_CERT%
DEL /Q %USR_SECURITY_FOLDER%\%CLIENT_AUTH_CERT%