#!/bin/bash

rm -Rf $JRE_SECURITY_FOLDER\$TRUSTED_CA
rm -Rf $JRE_SECURITY_FOLDER\$TRUSTED_SITE_CA

rm -Rf $JRE_SECURITY_FOLDER\$TRUSTED_CERT
rm -Rf $JRE_SECURITY_FOLDER\$TRUSTED_SITE_CERT
rm -Rf $JRE_SECURITY_FOLDER\$CLIENT_AUTH_CERT

rm -Rf $SYSTEM_SECURITY_FOLDER\$TRUSTED_CERT
rm -Rf $SYSTEM_SECURITY_FOLDER\$TRUSTED_SITE_CERT
rm -Rf $SYSTEM_SECURITY_FOLDER\$CLIENT_AUTH_CERT

rm -Rf $USR_SECURITY_FOLDER\$TRUSTED_CERT
rm -Rf $USR_SECURITY_FOLDER\$TRUSTED_SITE_CERT
rm -Rf $USR_SECURITY_FOLDER\$CLIENT_AUTH_CERT